### ISSUE TITLE
mod doesn't work properly across surfaces or dimensions

### ISSUE THREAD

**Issue by SophisticaSean** [Peppe-KSP/InterfaceChest#1]
entities are stored in the global entity list via modTick and their x y coordinates. Because x y coordinates can be the same now, due to multi dimensions/surfaces, we need something safer to key off of.

the bug causes entities from this mod to stop working when another entity from this mod is placed in the same x y coordinates and the modTick value is the same, this happens because the new entity overwrites the old entity in the entity list (due to having the same key values).

**Comment by Peppe-KSP** [comment]
Thanks for the fix.
